<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()) : ?>
    <div class="block filter">


        <div class="block-content filter-content">

            <div class="filter-content-title">
                <strong><?= $block->escapeHtml(__('Filter')) ?></strong>
            </div>

            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>"
                       class="action clear filter-clear"><span><?= $block->escapeHtml(__('Clear All')) ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter) : ?>
        <?php if (!$wrapOptions) : ?>
            <!--            <strong role="heading" aria-level="2"-->
            <!--                    class="block-subtitle filter-subtitle">--><?php //= $block->escapeHtml(__('Shopping Options')) ?><!--</strong>-->
            <dl class="filter-options" id="narrow-by-list">
                <?php $wrapOptions = true;
                endif; ?>
                <?php if ($filter->getItemsCount()) : ?>
                    <div class="filter-options-item">
                        <dt role="heading" aria-level="3"
                            class="filter-options-title"><?= $block->escapeHtml(__($filter->getName())) ?></dt>
                        <dd style="display: none" class="filter-options-content"><?= /* @noEscape */
                            $block->getChildBlock('renderer')->render($filter) ?></dd>
                    </div>

                <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($wrapOptions) : ?>
            </dl>
        <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
